spring:
  application:
    name: tournament
  datasource:
    url: jdbc:postgresql://localhost:5432/tournament
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
