server:
  port: 8081

spring:
  application:
    name: tournament
<<<<<<< HEAD
  datasource:
    url: jdbc:postgresql://localhost:5432/tournament
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
=======
<<<<<<< HEAD
=======
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
>>>>>>> origin/feature/crear-entidades-torneo
>>>>>>> develop
