CREATE TABLE tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    game_name VARCHAR(100) NOT NULL,
    tournament_format VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    max_participants INTEGER NOT NULL,
    registration_start_at TIMESTAMP,
    registration_end_at TIMESTAMP,
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    CONSTRAINT chk_tournaments_format
        CHECK (tournament_format IN ('SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'ROUND_ROBIN', 'SWISS')),
    CONSTRAINT chk_tournaments_status
        CHECK (status IN ('DRAFT', 'REGISTRATION_OPEN', 'REGISTRATION_CLOSED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_tournaments_max_participants
        CHECK (max_participants >= 2)
);

CREATE TABLE tournament_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tournament_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(30) NOT NULL,
    start_at TIMESTAMP,
    end_at TIMESTAMP,
    CONSTRAINT fk_tournament_rounds_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE,
    CONSTRAINT uk_tournament_rounds_tournament_round_number
        UNIQUE (tournament_id, round_number),
    CONSTRAINT chk_tournament_rounds_number
        CHECK (round_number >= 1),
    CONSTRAINT chk_tournament_rounds_status
        CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE TABLE tournament_prizes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tournament_id BIGINT NOT NULL,
    prize_position INTEGER NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    prize_type VARCHAR(30) NOT NULL,
    amount DECIMAL(12, 2),
    currency VARCHAR(3),
    CONSTRAINT fk_tournament_prizes_tournament
        FOREIGN KEY (tournament_id) REFERENCES tournaments (id) ON DELETE CASCADE,
    CONSTRAINT uk_tournament_prizes_tournament_position
        UNIQUE (tournament_id, prize_position),
    CONSTRAINT chk_tournament_prizes_position
        CHECK (prize_position >= 1),
    CONSTRAINT chk_tournament_prizes_type
        CHECK (prize_type IN ('CASH', 'POINTS', 'ITEM', 'OTHER')),
    CONSTRAINT chk_tournament_prizes_amount
        CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT chk_tournament_prizes_currency
        CHECK (currency IS NULL OR CHAR_LENGTH(currency) = 3)
);

CREATE INDEX idx_tournament_rounds_tournament_id
    ON tournament_rounds (tournament_id);

CREATE INDEX idx_tournament_prizes_tournament_id
    ON tournament_prizes (tournament_id);
